### ISSUE TITLE
asap not found?

### ISSUE THREAD

**Issue by ymilesz** [jolobito/SPdel#47]
Hi I am trying to run the test data with SPdel, but I am getting the following error:

Traceback (most recent call last):
  File "/home/zhangy/miniconda3/envs/spdel/bin/SPdel.py", line 1202, in <module>
    main()
  File "/home/zhangy/miniconda3/envs/spdel/bin/SPdel.py", line 1193, in main
    run(fasta,a,tree,CODE,dis,niter,sample,burnin,gen,sp,specList,n_ind,nocons,XList,PTPList,bPTPList,GMYCList,CompList,diagnostic)
  File "/home/zhangy/miniconda3/envs/spdel/bin/SPdel.py", line 947, in run
    distances=run_ASAP(basepath,inputs,gen,sp,dis)
  File "/home/zhangy/miniconda3/envs/spdel/bin/SPdel.py", line 845, in run_ASAP
    subprocess.call(['asap', '-d', d, '-o',os.path.join(basepath, 'ASAP'), file])
  File "/home/zhangy/miniconda3/envs/spdel/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/zhangy/miniconda3/envs/spdel/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/zhangy/miniconda3/envs/spdel/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'asap'

Also the example in the readme file is outdated, if possible please update that to make following along easier.

Thanks,

Miles

**Comment by maycol1551** [comment]
> example in the readme file is outdated, if possible please update that to make following along

I encountered the same issue. In the end I used the -X option to add the results from ASAP and ABGD in a csv

**Comment by jolobito** [comment]
Hi @ymilesz . Thanks for use SPdel. The README is now updated!
To find exactly the error I need some information:
1. Are you using the commnad line or jupyter version?
2. What is your OS?

It seems like the asap binary was not correctly instaled for some reason. I noted that in some computer the antivirus could block the installation.

**Comment by ymilesz** [comment]
Hi Jorge,

  1. I am using the command line version
  2. It is a Linux cluster, CentOS 8.5 perhaps?

**Comment by jolobito** [comment]
Can you check the content of this folder /home/zhangy/miniconda3/envs/spdel/bin ??

**Comment by ymilesz** [comment]
2to3
2to3-3.10
abgd_linux
asap_linux
aserver
assistant
attr
autopoint
balsam
bPTP.py
bunzip2
bzcat
bzcmp
bzdiff
bzegrep
bzfgrep
bzgrep
bzip2
bzip2recover
bzless
bzmore
cairo-trace
canbusutil
captoinfo
certutil
cjpeg
clear
compile_et
c_rehash
cups-config
cwebp
dbus-cleanup-sockets
dbus-daemon
dbus-launch
dbus-monitor
dbus-run-session
dbus-send
dbus-test-tool
dbus-update-activation-environment
dbus-uuidgen
derb
designer
Diagnoser.py
djpeg
dumpsexp
dwebp
envsubst
ete3
f2py
fc-cache
fc-cat
fc-conflist
fc-list
fc-match
fc-pattern
fc-query
fc-scan
fc-validate
fixqt4headers.pl
flac
fonttools
freetype-config
futurize
gapplication
gdbus
gdbus-codegen
genbrk
gencfu
gencnval
gendict
genrb
getfattr
gettext
gettextize
gettext.sh
gif2rgb
gif2webp
gifbuild
gifclrmp
giffix
giftext
giftool
gio
gio-querymodules
glib-compile-resources
glib-compile-schemas
glib-genmarshal
glib-gettextize
glib-mkenums
GMYC.py
gobject-query
gpg-error
gpgrt-config
gresource
gsettings
gss-client
gst-device-monitor-1.0
gst-discoverer-1.0
gst-inspect-1.0
gst-launch-1.0
gst-play-1.0
gst-stats-1.0
gst-typefind-1.0
gtester
gtester-report
hb-info
hb-ot-shape-closure
hb-shape
hb-subset
hb-view
hmac256
iconv
icu-config
icuexportdata
icuinfo
idle3
idle3.10
img2webp
infocmp
infotocap
ippeveprinter
ipptool
ipython
ipython3
jlpm
jpegtran
jpgicc
jsonpointer
jsonschema
jupyter
jupyter-dejavu
jupyter-events
jupyter-execute
jupyter-kernel
jupyter-kernelspec
jupyter-lab
jupyter-labextension
jupyter-labhub
jupyter-migrate
jupyter-nbconvert
jupyter-notebook
jupyter-run
jupyter-server
jupyter-troubleshoot
jupyter-trust
k5srvutil
kadmin
kaleido
KaleidoApp
kdestroy
keyctl
kinit
klist
kpasswd
krb5-config
ksu
kswitch
ktutil
kvno
lame
lconvert
libdeflate-gunzip
libdeflate-gzip
libgcrypt-config
libpng16-config
libpng-config
linguist
linkicc
lprodump
lrelease
lrelease-pro
lupdate
lupdate-pro
lz4
lz4c
lz4cat
lzcat
lzcmp
lzdiff
lzegrep
lzfgrep
lzgrep
lzless
lzma
lzmadec
lzmainfo
lzmore
makeconv
mathjax-path
meshdebug
metaflac
moc
mpg123
mpg123-id3dump
mpg123-strip
mpicalc
mptp_linux
msgattrib
msgcat
msgcmp
msgcomm
msgconv
msgen
msgexec
msgfilter
msgfmt
msggrep
msginit
msgmerge
msgunfmt
msguniq
ncurses6-config
ncursesw6-config
ngettext
normalizer
nspr-config
nss-config
openssl
opj_compress
opj_decompress
opj_dump
out123
pacat
pactl
padsp
pa-info
pamon
paplay
parec
parecord
pasteurize
pcre2-config
pcre2grep
pcre2_jit_test
pcre2posix_test
pcre2test
pg_config
pip
pip3
pixeltool
pk12util
pkgdata
pngfix
png-fix-itxt
prichunkpng
pricolpng
priditherpng
priforgepng
prigreypng
pripalpng
pripamtopng
priplan9topng
pripnglsch
pripngtopam
prirowpng
priweavepng
psicc
PTP.py
pybabel
__pycache__
pydoc
pydoc3
pydoc3.10
pyftmerge
pyftsubset
pygmentize
pyjson5
pylupdate5
pyrcc5
python
python3
python3.1
python3.10
python3.10-config
python3-config
pyuic5
qcollectiongenerator
qdbus
qdbuscpp2xml
qdbusviewer
qdbusxml2cpp
qdistancefieldgenerator
qdoc
qgltf
qhelpgenerator
qlalr
qmake
qml
qmlcachegen
qmleasing
qmlformat
qmlimportscanner
qmllint
qmlmin
qmlplugindump
qmlpreview
qmlprofiler
qmlscene
qmltestrunner
qmltime
qmltyperegistrar
qscxmlc
qtattributionsscanner
qt.conf
qtdiag
qtpaths
qtplugininfo
qvkgen
qwebengine_convert_dict
rcc
rdjpgcom
recode-sr-latin
repc
reset
sclient
send2trash
setfattr
sim_client
sip-build
sip-distinfo
sip-install
sip-module
sip-sdist
sip-wheel
sndfile-cmp
sndfile-concat
sndfile-convert
sndfile-deinterleave
sndfile-info
sndfile-interleave
sndfile-metadata-get
sndfile-metadata-set
sndfile-play
sndfile-salvage
SPdel.py
sqlite3
sqlite3_analyzer
summary.py
syncqt.pl
tabs
tclsh
tclsh8.6
tic
tiffcp
tiffdump
tiffinfo
tiffset
tiffsplit
tificc
tjbench
toe
tput
tracegen
transicc
tset
ttx
uic
unlz4
unlzma
unxz
unzstd
uuclient
webpinfo
webpmux
wheel
wish
wish8.6
wrjpgcom
wsdump
x86_64-conda_cos6-linux-gnu-ld
x86_64-conda-linux-gnu-ld
xgettext
xkbcli
xml2-config
xmlcatalog
xmllint
xmlpatterns
xmlpatternsvalidator
xmlwf
xslt-config
xsltproc
xz
xzcat
xzcmp
xzdec
xzdiff
xzegrep
xzfgrep
xzgrep
xzless
xzmore
yat2m
zstd
zstdcat
zstdgrep
zstdless
zstdmt

**Comment by jolobito** [comment]
Try running 

```
asap -h
```
or

``` 
home/zhangy/miniconda3/envs/spdel/bin/asap_linux -h
```

or

``` 
chmod +x home/zhangy/miniconda3/envs/spdel/bin/asap_linux
home/zhangy/miniconda3/envs/spdel/bin/asap_linux -h
```

any of these works?

**Comment by ymilesz** [comment]
first one didn't work, second asked for permission, so after chmod +x I got the following:

asap_linux: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by asap_linux)

**Comment by jolobito** [comment]
Hi @ymilesz 
We update the SPdel for this issue. Please download and install again. Let us know if the issue persists or if it is now resolved.

**Comment by ymilesz** [comment]
Hi I am getting different errors now after reinstalling SPdel:

`Following the example I did: SPdel.py path/Megaleporinus_COI.fasta -n -A -S -P -T -G -t path/Megaleporinus_tree.nwk`

and I got 

  ```
File "/home/zhangy/miniconda3/envs/spdel/bin/SPdel.py", line 1246, in <module>
    main()
  File "/home/zhangy/miniconda3/envs/spdel/bin/SPdel.py", line 1237, in main
    run(fasta,a,tree,CODE,dis,niter,sample,burnin,gen,sp,specList,n_ind,nocons,XList,PTPList,bPTPList,GMYCList,CompList,diagnostic)
  File "/home/zhangy/miniconda3/envs/spdel/bin/SPdel.py", line 986, in run
    distances.plot_freq(cmd=True)
  File "/home/zhangy/miniconda3/envs/spdel/lib/python3.10/site-packages/spdelib/Matrian.py", line 231, in plot_freq
    max_counts_tra = max(counts_tra)
ValueError: max() arg is an empty sequence
```

**Comment by Ulises-Rosas** [comment]
Did you provide a complete location for the `Megaleporinus_COI.fasta` file? i.e., did you change `path` in `path/Megaleporinus_COI.fasta` for the correct path?

**Comment by ymilesz** [comment]
Hi yes I did:

`python SPdel.py /scratch/usda_sel/zhangy/SPdel/data/Megaleporinus/Megaleporinus_COI.fasta -n -A -S -P -T -G -t /scratch/usda_sel/zhangy/SPdel/data/Megaleporinus/Megaleporinus_tree.nwk`

**Comment by jolobito** [comment]
Hi @ymilesz. It seems to be a issue with abgd compilation for linux. I updated again witha new binary. Please reinstall and check if the issue is solved.
Thanks for help us to improve SPdel!

**Comment by ymilesz** [comment]
Hi I am still getting that same error?

Traceback (most recent call last):
  File "/scratch/usda_sel/zhangy/SPdel/SPdel.py", line 1246, in <module>
    main()
  File "/scratch/usda_sel/zhangy/SPdel/SPdel.py", line 1237, in main
    run(fasta,a,tree,CODE,dis,niter,sample,burnin,gen,sp,specList,n_ind,nocons,XList,PTPList,bPTPList,GMYCList,CompList,diagnostic)
  File "/scratch/usda_sel/zhangy/SPdel/SPdel.py", line 986, in run
    distances.plot_freq(cmd=True)
  File "/scratch/usda_sel/zhangy/SPdel/spdelib/Matrian.py", line 231, in plot_freq
    max_counts_tra = max(counts_tra)
ValueError: max() arg is an empty sequence

**Comment by jolobito** [comment]
HI @ymilesz 
1. Can you try:

`python SPdel.py /scratch/usda_sel/zhangy/SPdel/data/Megaleporinus/Megaleporinus_COI.fasta -n -S -P -T -G -t /scratch/usda_sel/zhangy/SPdel/data/Megaleporinus/Megaleporinus_tree.nwk`

without -A to test if ABGD is the source of the issue.

2. Also, check in the Megaleporinus_COI.rec.spart file in the ABGD folder (should be in SPdel/data/Megaleporinus/ ) the line after "[Barcode gap distance :]". Shoul be shomething like:

[1.00e-03 / 1.67e-03 / 2.78e-03 / 4.64e-03 / 7.74e-03 / 1.29e-02 / 2.15e-02 / 3.593814e-02]

Thanks

**Comment by ymilesz** [comment]
Hello again

1. It did finish without -A
2. They all said 0

`begin spart;
Project_name = Megaleporinus_COI;
Date = 1969-12-31T19:00:00;
N_spartitions = 7 : Megaleporinus_COI_abgd_rec_1 / Megaleporinus_COI_abgd_rec_2 / Megaleporinus_COI_abgd_rec_3 / Megaleporinus_COI_abgd_rec_4 / Megaleporinus_COI_abgd_rec_5 / Megaleporinus_COI_abgd_rec_6 / Megaleporinus_COI_abgd_rec_7;
N_individuals = 116 / 116 / 116 / 116 / 116 / 116 /  116;
N_subsets = 27 / 27 / 19 / 18 / 16 / 16 / 15;
[Generated by ABGD with Distance K80 Kimura / MinSlope = 1.500000]
[Barcode gap distance :]
[0.00e+00 / 0.00e+00 / 0.00e+00 / 0.00e+00 / 0.00e+00 / 0.00e+00 / 0.000000e+00]
[WARNING: The sample names below may have been changed to fit SPART specification (only alphanumeric characters and _ )]
`
